authentication/urls.py
from django.urls import path
from authentication.views import login, logout

app_name = 'authentication'

urlpatterns = [
    path('login/', login, name='login'),
    path('logout/', logout, name='logout'),
]

in_stock/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('auth/', include('authentication.urls')), 
]

main/urls.py
from django.urls import path
from main.views import show_main, create_product, show_xml, show_json, show_xml_by_id, show_json_by_id, register, login_user, logout_user, edit_product, delete_product, get_product_json, add_product_ajax, create_product_flutter



app_name = 'main'

urlpatterns = [
    path('', show_main, name='show_main'),
    path('create-product', create_product, name='create_product'),
    path('xml/', show_xml, name='show_xml'),
    path('json/', show_json, name='show_json'),
    path('xml/<int:id>/', show_xml_by_id, name='show_xml_by_id'),
    path('json/<int:id>/', show_json_by_id, name='show_json_by_id'), 
    path('register/', register, name='register'),
    path('login/', login_user, name='login'),
    path('logout/', logout_user, name='logout'),
    path('edit-product/<int:id>', edit_product, name='edit_product'),
    path('delete/<int:id>', delete_product, name='delete_product'),
    path('get-product/', get_product_json, name='get_product_json'),
    path('create-product-ajax/', add_product_ajax, name='add_product_ajax'),
    path('create-flutter/', create_product_flutter, name='create_product_flutter'),
]

authentication/models.py
from django.db import models

# Create your models here.

main/models.py
from django.db import models
from django.contrib.auth.models import User

class Item(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    name = models.CharField(max_length=255)
    amount = models.IntegerField()
    description = models.TextField()

main/forms.py
from django.forms import ModelForm
from main.models import Item

class ProductForm(ModelForm):
    class Meta:
        model = Item
        fields = ["name", "amount", "description"]

authentication/views.py
from django.shortcuts import render
from django.contrib.auth import authenticate, login as auth_login
from django.http import JsonResponse
from django.views.decorators.csrf import csrf_exempt
from django.contrib.auth import logout as auth_logout

@csrf_exempt
def login(request):
    username = request.POST['username']
    password = request.POST['password']
    user = authenticate(username=username, password=password)
    if user is not None:
        if user.is_active:
            auth_login(request, user)
            # Status login sukses.
            return JsonResponse({
                "username": user.username,
                "status": True,
                "message": "Login sukses!"
                # Tambahkan data lainnya jika ingin mengirim data ke Flutter.
            }, status=200)
        else:
            return JsonResponse({
                "status": False,
                "message": "Login gagal, akun dinonaktifkan."
            }, status=401)

    else:
        return JsonResponse({
            "status": False,
            "message": "Login gagal, periksa kembali email atau kata sandi."
        }, status=401)
    
@csrf_exempt
def logout(request):
    username = request.user.username

    try:
        auth_logout(request)
        return JsonResponse({
            "username": username,
            "status": True,
            "message": "Logout berhasil!"
        }, status=200)
    except:
        return JsonResponse({
        "status": False,
        "message": "Logout gagal."
        }, status=401)
    

main/views.py
import datetime
import json
from django.http import HttpResponseNotFound, HttpResponseRedirect, JsonResponse
from django.urls import reverse
from django.contrib.auth.decorators import login_required
from django.views.decorators.csrf import csrf_exempt
from django.contrib.auth import authenticate, login, logout
from django.shortcuts import redirect
from django.contrib.auth.forms import UserCreationForm
from django.contrib import messages
from django.shortcuts import render
from django.http import HttpResponseRedirect
from main.forms import ProductForm
from django.urls import reverse
from main.models import Item
from django.http import HttpResponse
from django.core import serializers


# Create your views here.
@login_required(login_url='/login')
def show_main(request):
    products = Item.objects.filter(user=request.user)
    context = {
        'name': request.user.username,
        'class': 'PBP E',
        'products': products,
        'last_login': request.COOKIES['last_login'],
    }

    return render(request, "main.html", context)

def create_product(request):
    form = ProductForm(request.POST or None)

    if form.is_valid() and request.method == "POST":
        product = form.save(commit=False)
        product.user = request.user
        product.save()
        return HttpResponseRedirect(reverse('main:show_main'))

    context = {'form': form}
    return render(request, "create_product.html", context)

def show_xml(request):
    data = Item.objects.all()
    return HttpResponse(serializers.serialize("xml", data), content_type="application/xml")

def show_json(request):
    data = Item.objects.all()
    return HttpResponse(serializers.serialize("json", data), content_type="application/json")

def show_xml_by_id(request, id):
    data = Item.objects.filter(pk=id)
    return HttpResponse(serializers.serialize("xml", data), content_type="application/xml")

def show_json_by_id(request, id):
    data = Item.objects.filter(pk=id)
    return HttpResponse(serializers.serialize("json", data), content_type="application/json")

def register(request):
    form = UserCreationForm()

    if request.method == "POST":
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, 'Your account has been successfully created!')
            return redirect('main:login')
    context = {'form':form}
    return render(request, 'register.html', context)

def login_user(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            response = HttpResponseRedirect(reverse("main:show_main")) 
            response.set_cookie('last_login', str(datetime.datetime.now()))
            return response
        else:
            messages.info(request, 'Sorry, incorrect username or password. Please try again.')
    context = {}
    return render(request, 'login.html', context)

def logout_user(request):
    logout(request)
    response = HttpResponseRedirect(reverse('main:login'))
    response.delete_cookie('last_login')
    return response

def edit_product(request, id):
    # Get product berdasarkan ID
    product = Item.objects.get(pk = id)

    # Set product sebagai instance dari form
    form = ProductForm(request.POST or None, instance=product)

    if form.is_valid() and request.method == "POST":
        # Simpan form dan kembali ke halaman awal
        form.save()
        return HttpResponseRedirect(reverse('main:show_main'))

    context = {'form': form}
    return render(request, "edit_product.html", context)

def delete_product(request, id):
    # Get data berdasarkan ID
    product = Item.objects.get(pk = id)
    # Hapus data
    product.delete()
    # Kembali ke halaman awal
    return HttpResponseRedirect(reverse('main:show_main'))

def get_product_json(request):
    product_item = Item.objects.all()
    return HttpResponse(serializers.serialize('json', product_item))

@csrf_exempt
def add_product_ajax(request):
    if request.method == 'POST':
        name = request.POST.get("name")
        amount = request.POST.get("amount")
        description = request.POST.get("description")
        user = request.user

        new_product = Item(name=name, amount=amount, description=description, user=user)
        new_product.save()

        return HttpResponse(b"CREATED", status=201)

    return HttpResponseNotFound()

@csrf_exempt
def create_product_flutter(request):
    if request.method == 'POST':
        
        data = json.loads(request.body)

        new_product = Item.objects.create(
            user = request.user,
            name = data["name"],
            amount = int(data["amount"]),
            description = data["description"]
        )

        new_product.save()

        return JsonResponse({"status": "success"}, status=200)
    else:
        return JsonResponse({"status": "error"}, status=401)

main/templates/create_product.html
{% extends 'base.html' %} 

{% block content %}
<style>
    body {
    background-color: #b99174; /* Change to the desired background color */
    margin: 0; /* Remove default body margin */
    padding: 0; /* Remove default body padding */
}
.template {
    background-color: #f3f2dc;
    display: flex;
    flex-direction: column;
    align-items: center;
    justify-content: center;
    margin-top: 200px;
    margin-bottom: 200px;
    margin-right: 200px;
    margin-left: 200px;
    font-family: "Times New Roman", sans-serif;
    font-weight: bold;
    border: 1px solid #00000000;
    padding-top: 100px;
    padding-bottom: 100px;
    border-radius: 10px;
    box-sizing: border-box;
    border-style: ridge;
    line-height: 3;
}
</style>
<div class ="template">
<h1>Add New Product</h1>

<form method="POST">
    {% csrf_token %}
    <table>
        {{ form.as_table }}
        <tr>
            <td></td>
            <td>
                <input type="submit" value="Add Product"/>
            </td>
        </tr>
    </table>
</form>
</div>

{% endblock %}

main/templates/edit_product.html
{% extends 'base.html' %}

{% load static %}

{% block content %}
<style>
        body {
        background-color: #b99174; /* Change to the desired background color */
        margin: 0; /* Remove default body margin */
        padding: 0; /* Remove default body padding */
    }
    .template {
        background-color: #f3f2dc;
        display: flex;
        flex-direction: column;
        align-items: center;
        justify-content: center;
        margin-top: 200px;
        margin-bottom: 200px;
        margin-right: 200px;
        margin-left: 200px;
        font-family: "Times New Roman", sans-serif;
        font-weight: bold;
        border: 1px solid #00000000;
        padding-top: 100px;
        padding-bottom: 100px;
        border-radius: 10px;
        box-sizing: border-box;
        border-style: ridge;
        line-height: 3;
    }
</style>

<div class="template">
    <h1>Edit Product</h1>

    <form method="POST">
        {% csrf_token %}
        <table>
            {{ form.as_table }}
            <tr>
                <td></td>
                <td>
                    <input type="submit" value="Edit Product"/>
                </td>
            </tr>
        </table>
    </form>
</div>

{% endblock %}

main/templates/login.html
{% extends 'base.html' %}

{% block meta %}
    <title>Login</title>
{% endblock meta %}

{% block content %}

<style>
    body {
        background-color: #b99174; /* Change to the desired background color */
        margin: 0; /* Remove default body margin */
        padding: 0; /* Remove default body padding */
    }
    .login {
        background-color: #f3f2dc;
        display: flex;
        flex-direction: column;
        align-items: center;
        justify-content: center;
        margin-top: 200px;
        margin-bottom: 200px;
        margin-right: 200px;
        margin-left: 200px;
        font-family: "Times New Roman", sans-serif;
        font-weight: bold;
        border: 1px solid #00000000;
        padding-top: 100px;
        padding-bottom: 100px;
        border-radius: 10px;
        box-sizing: border-box;
        border-style: ridge;
        line-height: 3;
    }

    .login_btn {
        background-color: #f0d121aa; /* Change the background color */
        color: #fff; /* Change the text color */
        padding: 0px 20px; /* Adjust padding for button size */
        border: none; /* Remove button border */
        cursor: pointer;
        font-weight: bold;
        border-radius: 3px; /* Rounded corners */
        text-transform: uppercase; /* Convert text to uppercase */
    }

    .form-control {
        font-family: 'Open Sans', sans-serif;
        line-height: 1.5;
        display: block;
        width: 150%;
        padding: 5px;
        font-size: 16px;
        border: 1px solid #030303;
        background-color: #ffffff;
        border-radius: 15px;
        margin-bottom: 8px;
    }
    .register-text {
        white-space: nowrap; /* Prevent line breaks within the text */
    }
</style>


<div class = "login">

    <h1 style="font-weight: bold;">Login</h1>

    <form method="POST" action="">
        {% csrf_token %}
        <table>
            <tr>
                <td><input type="text" name="username" placeholder="Username" class="form-control"></td>
            </tr>
            <tr>
                <td><input type="password" name="password" placeholder="Password" class="form-control"></td>
            </tr>

            <tr>
                <td></td>
                <br />
                <td><button type="submit" class="btn login_btn">Login</button></td>
            </tr>
        </table>
    </form>

    {% if messages %}
        <ul>
            {% for message in messages %}
                <li>{{ message }}</li>
            {% endfor %}
        </ul>
    {% endif %}     
        
    <p class="register-text">Don't have an account yet? <a href="{% url 'main:register' %}">Register Now</a></p>

</div>

{% endblock content %}

main/templates/main.html
{% extends 'base.html' %}

{% block meta %}
    <title>In Stock Homepage</title>
{% endblock meta %}

{% block content %}
<style>
    body {
        font-family: 'Open Sans', sans-serif;
        background-color: #fcfaf8; /* Change to the desired background color */
        margin: 0; /* Remove default body margin */
        padding: 0; /* Remove default body padding */
    }

    .card-style{
        width: 300px; 
        margin: 20px; /* Adjust the margin as needed */
        padding: 15px;
        background-color: #fff; /* Card background color */
        border: 1px solid #ddd;
        border-radius: 8%;
    }
    .custom-bg-color {
        background-color: #f0c012fc; /* Replace with your desired custom color */
        /* You can add more CSS properties here for styling */
    }
    .bg-color{
        background-color: #fcfaf8;
    }
    .register-text {
        white-space: nowrap; /* Prevent line breaks within the text */
    }
    .add_btn {
        padding: 0px 5px; 
        border: none; 
        cursor: pointer;
        font-weight: bold;
        font-size: 90px;
        border-radius: 50%;
        width: 150px;
        height: 150px;
        display: inline-block;
    }
</style>

<div class="container-fluid p-1 custom-bg-color text-white text-center">
    
    <h1>In Stock Page</h1>
    <h5>Welcome! {{name}} from {{ class }}</h5>
    <div style="position: fixed; top: 10px; right: 10px;">
        <p>Sesi terakhir login: {{ last_login }}</p>
    </div>
</div>
<div class="d-flex flex-wrap justify-content-center" id="product_container"></div>
<div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h1 class="modal-title fs-5" id="exampleModalLabel">Add New Product</h1>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <form id="form" onsubmit="return false;">
                    {% csrf_token %}
                    <div class="mb-3">
                        <label for="name" class="col-form-label">Name:</label>
                        <input type="text" class="form-control" id="name" name="name"></input>
                    </div>
                    <div class="mb-3">
                        <label for="amount" class="col-form-label">Amount:</label>
                        <input type="number" class="form-control" id="amount" name="amount"></input>
                    </div>
                    <div class="mb-3">
                        <label for="description" class="col-form-label">Description:</label>
                        <textarea class="form-control" id="description" name="description"></textarea>
                    </div>
                </form>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                <button type="button" class="btn btn-primary" id="button_add" data-bs-dismiss="modal">Add Product</button>
            </div>
        </div>
    </div>
</div>


<br />
<div class="container d-grid gap-5 justify-content-center">
    <button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#exampleModal" style="width: 200px;">Add Product</button>
</div>
<br />
<div class="container d-grid gap-5 text-center">
    <a href="{% url 'main:logout' %}">
        <button type="button" class="btn btn-dark btn-block"  style="width: 200px;">Logout</button>
    </a>
</div>
<script>
    async function getProducts() {
        return fetch("{% url 'main:get_product_json' %}").then((res) => res.json())
    }
    async function refreshProducts() {
        document.getElementById("product_container").innerHTML = ""
        const products = await getProducts()
        products.forEach((item) => {
        const card = document.createElement("div");
        card.classList.add("card-style");

        const name = document.createElement("h3");
        name.textContent = item.fields.name;
        name.classList.add("text-center", "bold");

        const amount = document.createElement("h5");
        amount.textContent = `Amount: ${item.fields.amount}`;
        amount.classList.add("text-center");

        const description = document.createElement("p");
        description.textContent = item.fields.description;
        description.classList.add("text-center");

        const editButton = document.createElement("button");
        editButton.textContent = "Edit";
        editButton.classList.add("edit-button");
        editButton.classList.add("btn", "btn-primary", "btn-block", "register-text");
        editButton.style.width = "50%";
        editButton.addEventListener("click", () => {
            window.location.href = `edit-product/${item.pk}`;
        });
        editButton.classList.add("text-center");
        const deleteButton = document.createElement("button");
        deleteButton.textContent = "Delete";
        deleteButton.classList.add("delete-button");
        deleteButton.classList.add("btn", "btn-danger", "btn-block", "register-text");
        deleteButton.style.width = "50%";
        deleteButton.addEventListener("click", () => {
            window.location.href = `delete/${item.pk}`;
        });
        deleteButton.classList.add("text-center");

        card.appendChild(name);
        card.appendChild(amount);
        card.appendChild(description);
        card.appendChild(editButton);
        card.appendChild(deleteButton);

        document.getElementById("product_container").appendChild(card);
        });
    }

    refreshProducts()

    function addProduct() {
        fetch("{% url 'main:add_product_ajax' %}", {
            method: "POST",
            body: new FormData(document.querySelector('#form'))
        }).then(refreshProducts)

        document.getElementById("form").reset()
        return false
    }
    document.getElementById("button_add").onclick = addProduct
</script>


{% endblock content %}

main/templates/register.html
{% extends 'base.html' %}

{% block meta %}
    <title>Register</title>
{% endblock meta %}

{% block content %}  
<style>
    body {
        background-color: #b99174; /* Change to the desired background color */
        margin: 0; /* Remove default body margin */
        padding: 0; /* Remove default body padding */
    }
    .regis {
        background-color: #f3f2dc;
        display: flex;
        flex-direction: column;
        align-items: center;
        justify-content: center;
        margin-top: 200px;
        margin-bottom: 200px;
        margin-right: 200px;
        margin-left: 200px;
        font-family: "Times New Roman", sans-serif;
        font-weight: bold;
        border: 1px solid #00000000;
        padding-top: 100px;
        padding-bottom: 100px;
        border-radius: 10px;
        box-sizing: border-box;
        border-style: ridge;
    }
    .daftar_btn {
        background-color: #f0d121aa; /* Change the background color */
        color: #fff; /* Change the text color */
        padding: 0px 20px; /* Adjust padding for button size */
        border: none; /* Remove button border */
        cursor: pointer;
        font-weight: bold;
        border-radius: 3px; /* Rounded corners */
        text-transform: uppercase; /* Convert text to uppercase */
    }
    .last-row {
        color: rgb(236, 29, 191); /* Warna teks jika diperlukan */
    }

</style>

<div class = "regis">
    
    <h1 style="font-weight: bold;">Welcome to In Stock!</h1>  
    <h3 style="font-weight: bold;">Regist Here</h3> 

        <form method="POST" >  
            {% csrf_token %}  
            <table>  
                {{ form.as_table }}  
                <tr>  
                    <td></td>
                    <br />
                    <td><input type="submit" name="submit" value="Daftar" style="width: 50%; font-family: 'Open Sans', sans-serif;
                        " class="btn btn-light btn-block daftar_btn"/></td>  
                </tr>  
            </table>  
        </form>

    {% if messages %}  
        <ul>   
            {% for message in messages %}  
                <li>{{ message }}</li>  
                {% endfor %}  
        </ul>   
    {% endif %}

</div>  

{% endblock content %}

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8" />
        <meta
            name="viewport"
            content="width=device-width, initial-scale=1.0"
        />
        {% block meta %}
        {% endblock meta %}
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
        <script src="https://code.jquery.com/jquery-3.6.0.min.js" integrity="sha384-KyZXEAg3QhqLMpG8r+J4jsl5c9zdLKaUk5Ae5f5b1bw6AUn5f5v8FZJoMxm6f5cH1" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js" integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.min.js" integrity="sha384-BBtl+eGJRgqQAUMxJ7pMwbEyER4l1g+O15P+16Ep7Q9Q+zqX6gSbd85u4mG4QzX+" crossorigin="anonymous"></script>    </head>

    <body>
        {% block content %}
        {% endblock content %}
    </body>
</html>